# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 551)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnMur = QtWidgets.QPushButton(self.centralwidget)
        self.btnMur.setGeometry(QtCore.QRect(60, 50, 121, 61))
        self.btnMur.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMur.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnMur.setObjectName("btnMur")
        self.btnMuraxaza = QtWidgets.QPushButton(self.centralwidget)
        self.btnMuraxaza.setGeometry(QtCore.QRect(60, 180, 121, 61))
        self.btnMuraxaza.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMuraxaza.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnMuraxaza.setObjectName("btnMuraxaza")
        self.btnPlanoInclinadoPolea = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlanoInclinadoPolea.setGeometry(QtCore.QRect(60, 320, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnPlanoInclinadoPolea.setFont(font)
        self.btnPlanoInclinadoPolea.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPlanoInclinadoPolea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnPlanoInclinadoPolea.setAutoFillBackground(False)
        self.btnPlanoInclinadoPolea.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnPlanoInclinadoPolea.setAutoRepeatDelay(300)
        self.btnPlanoInclinadoPolea.setFlat(False)
        self.btnPlanoInclinadoPolea.setObjectName("btnPlanoInclinadoPolea")
        self.btnMura = QtWidgets.QPushButton(self.centralwidget)
        self.btnMura.setGeometry(QtCore.QRect(220, 50, 121, 61))
        self.btnMura.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMura.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnMura.setObjectName("btnMura")
        self.btnPendulo = QtWidgets.QPushButton(self.centralwidget)
        self.btnPendulo.setGeometry(QtCore.QRect(220, 320, 121, 61))
        self.btnPendulo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPendulo.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnPendulo.setObjectName("btnPendulo")
        self.btnMurayaza = QtWidgets.QPushButton(self.centralwidget)
        self.btnMurayaza.setGeometry(QtCore.QRect(220, 180, 121, 61))
        self.btnMurayaza.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMurayaza.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnMurayaza.setObjectName("btnMurayaza")
        self.btnMuraxa = QtWidgets.QPushButton(self.centralwidget)
        self.btnMuraxa.setGeometry(QtCore.QRect(380, 50, 121, 61))
        self.btnMuraxa.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMuraxa.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnMuraxa.setObjectName("btnMuraxa")
        self.btnPenduloResorte = QtWidgets.QPushButton(self.centralwidget)
        self.btnPenduloResorte.setGeometry(QtCore.QRect(380, 320, 121, 61))
        self.btnPenduloResorte.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPenduloResorte.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnPenduloResorte.setObjectName("btnPenduloResorte")
        self.btnMura3 = QtWidgets.QPushButton(self.centralwidget)
        self.btnMura3.setGeometry(QtCore.QRect(380, 180, 121, 61))
        self.btnMura3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMura3.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnMura3.setObjectName("btnMura3")
        self.btnResorte = QtWidgets.QPushButton(self.centralwidget)
        self.btnResorte.setGeometry(QtCore.QRect(530, 320, 121, 61))
        self.btnResorte.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnResorte.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnResorte.setObjectName("btnResorte")
        self.btnMuraxaya = QtWidgets.QPushButton(self.centralwidget)
        self.btnMuraxaya.setGeometry(QtCore.QRect(530, 50, 121, 61))
        self.btnMuraxaya.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMuraxaya.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnMuraxaya.setObjectName("btnMuraxaya")
        self.btnPlanoInclinado = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlanoInclinado.setGeometry(QtCore.QRect(530, 180, 121, 61))
        self.btnPlanoInclinado.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPlanoInclinado.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnPlanoInclinado.setObjectName("btnPlanoInclinado")
        self.btnColisionLinealnelastica = QtWidgets.QPushButton(self.centralwidget)
        self.btnColisionLinealnelastica.setGeometry(QtCore.QRect(380, 430, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnColisionLinealnelastica.setFont(font)
        self.btnColisionLinealnelastica.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnColisionLinealnelastica.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnColisionLinealnelastica.setObjectName("btnColisionLinealnelastica")
        self.btnColisionLinealElastica = QtWidgets.QPushButton(self.centralwidget)
        self.btnColisionLinealElastica.setGeometry(QtCore.QRect(220, 430, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnColisionLinealElastica.setFont(font)
        self.btnColisionLinealElastica.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnColisionLinealElastica.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnColisionLinealElastica.setObjectName("btnColisionLinealElastica")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 120, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 120, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 120, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 120, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(220, 250, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 250, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(380, 250, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(60, 390, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(220, 500, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(380, 500, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setScaledContents(True)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnMur.setText(_translate("MainWindow", "MUR"))
        self.btnMuraxaza.setText(_translate("MainWindow", "MURAXAZA"))
        self.btnPlanoInclinadoPolea.setText(_translate("MainWindow", "PIP"))
        self.btnMura.setText(_translate("MainWindow", "MURA"))
        self.btnPendulo.setText(_translate("MainWindow", "PÉNDULO "))
        self.btnMurayaza.setText(_translate("MainWindow", "MURAYAZA"))
        self.btnMuraxa.setText(_translate("MainWindow", "MURAXA"))
        self.btnPenduloResorte.setText(_translate("MainWindow", "PÉNDULO RESORTE"))
        self.btnMura3.setText(_translate("MainWindow", "MURA3"))
        self.btnResorte.setText(_translate("MainWindow", "RESORTE"))
        self.btnMuraxaya.setText(_translate("MainWindow", "MURAXAYA"))
        self.btnPlanoInclinado.setText(_translate("MainWindow", "PLANO INCLINADO"))
        self.btnColisionLinealnelastica.setText(_translate("MainWindow", "CLIE"))
        self.btnColisionLinealElastica.setText(_translate("MainWindow", "CLE"))
        self.label.setText(_translate("MainWindow", "Movimiento Rectilineo Uniforme"))
        self.label_2.setText(_translate("MainWindow", "Movimiento Rectilineo Uniforme Acelerado"))
        self.label_3.setText(_translate("MainWindow", "Movimiento Rectilineo Uniforme Acelerado (x)"))
        self.label_4.setText(_translate("MainWindow", "Movimiento Rectilineo Uniforme Acelerado           (x, y)"))
        self.label_6.setText(_translate("MainWindow", "Movimiento Rectilineo Uniforme Acelerado           (y, z)"))
        self.label_7.setText(_translate("MainWindow", "Movimiento Rectilineo Uniforme Acelerado           (x, z)"))
        self.label_8.setText(_translate("MainWindow", "Movimiento Rectilineo Uniforme Acelerado (x,y,z)"))
        self.label_10.setText(_translate("MainWindow", "Plano Inclinado Polea"))
        self.label_9.setText(_translate("MainWindow", "Colision Lineal Elastica"))
        self.label_11.setText(_translate("MainWindow", "Colision Lineal Inelastica"))
