# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\peral\OneDrive\Escritorio\solve-dynamic-\Windows\desingUi\resorte.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogResorte(object):
    def setupUi(self, DialogResorte):
        DialogResorte.setObjectName("DialogResorte")
        DialogResorte.resize(226, 377)
        DialogResorte.setStyleSheet("background-color: #DFEAFF;")
        self.inptMasaObjeto = QtWidgets.QLineEdit(DialogResorte)
        self.inptMasaObjeto.setGeometry(QtCore.QRect(30, 100, 161, 20))
        self.inptMasaObjeto.setStyleSheet("background-color: white;")
        self.inptMasaObjeto.setObjectName("inptMasaObjeto")
        self.lblErrorMasaObjeto = QtWidgets.QLabel(DialogResorte)
        self.lblErrorMasaObjeto.setGeometry(QtCore.QRect(30, 120, 131, 16))
        self.lblErrorMasaObjeto.setText("")
        self.lblErrorMasaObjeto.setObjectName("lblErrorMasaObjeto")
        self.inptConstanteResorte = QtWidgets.QLineEdit(DialogResorte)
        self.inptConstanteResorte.setGeometry(QtCore.QRect(30, 260, 161, 20))
        self.inptConstanteResorte.setStyleSheet("background-color: white;")
        self.inptConstanteResorte.setObjectName("inptConstanteResorte")
        self.lblErrorConstanteResorte = QtWidgets.QLabel(DialogResorte)
        self.lblErrorConstanteResorte.setGeometry(QtCore.QRect(30, 280, 131, 16))
        self.lblErrorConstanteResorte.setText("")
        self.lblErrorConstanteResorte.setObjectName("lblErrorConstanteResorte")
        self.label_2 = QtWidgets.QLabel(DialogResorte)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(DialogResorte)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.inptDistanciaCompresion = QtWidgets.QLineEdit(DialogResorte)
        self.inptDistanciaCompresion.setGeometry(QtCore.QRect(30, 180, 161, 20))
        self.inptDistanciaCompresion.setStyleSheet("background-color: white;")
        self.inptDistanciaCompresion.setObjectName("inptDistanciaCompresion")
        self.lblErrorDistanciaCompresion = QtWidgets.QLabel(DialogResorte)
        self.lblErrorDistanciaCompresion.setGeometry(QtCore.QRect(30, 200, 131, 16))
        self.lblErrorDistanciaCompresion.setText("")
        self.lblErrorDistanciaCompresion.setObjectName("lblErrorDistanciaCompresion")
        self.label = QtWidgets.QLabel(DialogResorte)
        self.label.setGeometry(QtCore.QRect(30, 80, 111, 16))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(DialogResorte)
        self.label_4.setGeometry(QtCore.QRect(30, 240, 131, 16))
        self.label_4.setObjectName("label_4")
        self.btnSimular = QtWidgets.QPushButton(DialogResorte)
        self.btnSimular.setGeometry(QtCore.QRect(30, 320, 75, 23))
        self.btnSimular.setStyleSheet("background-color: #3D63DD;\n"
"color: white;")
        self.btnSimular.setObjectName("btnSimular")
        self.btnCancelar = QtWidgets.QPushButton(DialogResorte)
        self.btnCancelar.setGeometry(QtCore.QRect(120, 320, 75, 23))
        self.btnCancelar.setStyleSheet("background-color: #3D63DD;\n"
"color: white;")
        self.btnCancelar.setObjectName("btnCancelar")

        self.retranslateUi(DialogResorte)
        QtCore.QMetaObject.connectSlotsByName(DialogResorte)

    def retranslateUi(self, DialogResorte):
        _translate = QtCore.QCoreApplication.translate
        DialogResorte.setWindowTitle(_translate("DialogResorte", "Resorte"))
        self.label_2.setText(_translate("DialogResorte", "Distancia de compresion"))
        self.label_3.setText(_translate("DialogResorte", "Péndulo resorte"))
        self.label.setText(_translate("DialogResorte", "Masa del  objeto"))
        self.label_4.setText(_translate("DialogResorte", "Constante del resorte"))
        self.btnSimular.setText(_translate("DialogResorte", "Simular"))
        self.btnCancelar.setText(_translate("DialogResorte", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogResorte = QtWidgets.QDialog()
    ui = Ui_DialogResorte()
    ui.setupUi(DialogResorte)
    DialogResorte.show()
    sys.exit(app.exec_())
