# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\peral\OneDrive\Escritorio\solve-dynamic-\Windows\desingUi\colisionLinealInelastica .ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogColisionLinealInelastica(object):
    def setupUi(self, DialogColisionLinealInelastica):
        DialogColisionLinealInelastica.setObjectName("DialogColisionLinealInelastica")
        DialogColisionLinealInelastica.resize(644, 282)
        DialogColisionLinealInelastica.setStyleSheet("background-color: #DFEAFF;")
        self.lblErrorMasaLadrillo2 = QtWidgets.QLabel(DialogColisionLinealInelastica)
        self.lblErrorMasaLadrillo2.setGeometry(QtCore.QRect(240, 120, 131, 16))
        self.lblErrorMasaLadrillo2.setText("")
        self.lblErrorMasaLadrillo2.setObjectName("lblErrorMasaLadrillo2")
        self.inptMasaLadrillo1 = QtWidgets.QLineEdit(DialogColisionLinealInelastica)
        self.inptMasaLadrillo1.setGeometry(QtCore.QRect(30, 100, 161, 20))
        self.inptMasaLadrillo1.setStyleSheet("background-color: white;")
        self.inptMasaLadrillo1.setObjectName("inptMasaLadrillo1")
        self.lblErrorMasaLadrillo1 = QtWidgets.QLabel(DialogColisionLinealInelastica)
        self.lblErrorMasaLadrillo1.setGeometry(QtCore.QRect(30, 120, 131, 16))
        self.lblErrorMasaLadrillo1.setText("")
        self.lblErrorMasaLadrillo1.setObjectName("lblErrorMasaLadrillo1")
        self.label_3 = QtWidgets.QLabel(DialogColisionLinealInelastica)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 641, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.lblVelocidadLadrillo1 = QtWidgets.QLabel(DialogColisionLinealInelastica)
        self.lblVelocidadLadrillo1.setGeometry(QtCore.QRect(30, 190, 131, 16))
        self.lblVelocidadLadrillo1.setText("")
        self.lblVelocidadLadrillo1.setObjectName("lblVelocidadLadrillo1")
        self.label_2 = QtWidgets.QLabel(DialogColisionLinealInelastica)
        self.label_2.setGeometry(QtCore.QRect(240, 80, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(DialogColisionLinealInelastica)
        self.label_6.setGeometry(QtCore.QRect(450, 80, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(DialogColisionLinealInelastica)
        self.label_7.setGeometry(QtCore.QRect(240, 150, 161, 16))
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(DialogColisionLinealInelastica)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 161, 16))
        self.label_4.setObjectName("label_4")
        self.inptMasaLadrillo2 = QtWidgets.QLineEdit(DialogColisionLinealInelastica)
        self.inptMasaLadrillo2.setGeometry(QtCore.QRect(240, 100, 161, 20))
        self.inptMasaLadrillo2.setStyleSheet("background-color: white;")
        self.inptMasaLadrillo2.setObjectName("inptMasaLadrillo2")
        self.inptVelocidadLadrillo1 = QtWidgets.QLineEdit(DialogColisionLinealInelastica)
        self.inptVelocidadLadrillo1.setGeometry(QtCore.QRect(30, 170, 161, 20))
        self.inptVelocidadLadrillo1.setStyleSheet("background-color: white;")
        self.inptVelocidadLadrillo1.setObjectName("inptVelocidadLadrillo1")
        self.label = QtWidgets.QLabel(DialogColisionLinealInelastica)
        self.label.setGeometry(QtCore.QRect(30, 80, 111, 16))
        self.label.setObjectName("label")
        self.lblErrorDistanciaLadrillos = QtWidgets.QLabel(DialogColisionLinealInelastica)
        self.lblErrorDistanciaLadrillos.setGeometry(QtCore.QRect(450, 120, 131, 16))
        self.lblErrorDistanciaLadrillos.setText("")
        self.lblErrorDistanciaLadrillos.setObjectName("lblErrorDistanciaLadrillos")
        self.inptDistanciaLadrillos = QtWidgets.QLineEdit(DialogColisionLinealInelastica)
        self.inptDistanciaLadrillos.setGeometry(QtCore.QRect(450, 100, 161, 20))
        self.inptDistanciaLadrillos.setStyleSheet("background-color: white;")
        self.inptDistanciaLadrillos.setObjectName("inptDistanciaLadrillos")
        self.btnSimular = QtWidgets.QPushButton(DialogColisionLinealInelastica)
        self.btnSimular.setGeometry(QtCore.QRect(240, 230, 75, 23))
        self.btnSimular.setStyleSheet("background-color: #3D63DD;\n"
"color: white;")
        self.btnSimular.setObjectName("btnSimular")
        self.btnCancelar = QtWidgets.QPushButton(DialogColisionLinealInelastica)
        self.btnCancelar.setGeometry(QtCore.QRect(330, 230, 75, 23))
        self.btnCancelar.setStyleSheet("background-color: #3D63DD;\n"
"color: white;")
        self.btnCancelar.setObjectName("btnCancelar")

        self.retranslateUi(DialogColisionLinealInelastica)
        QtCore.QMetaObject.connectSlotsByName(DialogColisionLinealInelastica)

    def retranslateUi(self, DialogColisionLinealInelastica):
        _translate = QtCore.QCoreApplication.translate
        DialogColisionLinealInelastica.setWindowTitle(_translate("DialogColisionLinealInelastica", "Colisión lineal inelástica "))
        self.label_3.setText(_translate("DialogColisionLinealInelastica", "Colisión lineal inelástica "))
        self.label_2.setText(_translate("DialogColisionLinealInelastica", "Masa ladrillo 2"))
        self.label_6.setText(_translate("DialogColisionLinealInelastica", "Distancia entre ladrillos"))
        self.label_4.setText(_translate("DialogColisionLinealInelastica", "Velocidad incial ladrillo 1"))
        self.label.setText(_translate("DialogColisionLinealInelastica", "Masa ladrillo 1"))
        self.btnSimular.setText(_translate("DialogColisionLinealInelastica", "Simular"))
        self.btnCancelar.setText(_translate("DialogColisionLinealInelastica", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogColisionLinealInelastica = QtWidgets.QDialog()
    ui = Ui_DialogColisionLinealInelastica()
    ui.setupUi(DialogColisionLinealInelastica)
    DialogColisionLinealInelastica.show()
    sys.exit(app.exec_())
