# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\peral\OneDrive\Escritorio\solve-dynamic-\Windows\desingUi\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 412)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnMur = QtWidgets.QPushButton(self.centralwidget)
        self.btnMur.setGeometry(QtCore.QRect(60, 50, 121, 61))
        self.btnMur.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMur.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnMur.setObjectName("btnMur")
        self.btnMuraxaza = QtWidgets.QPushButton(self.centralwidget)
        self.btnMuraxaza.setGeometry(QtCore.QRect(60, 130, 121, 61))
        self.btnMuraxaza.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMuraxaza.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnMuraxaza.setObjectName("btnMuraxaza")
        self.btnPlanoInclinadoPolea = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlanoInclinadoPolea.setGeometry(QtCore.QRect(60, 210, 121, 61))
        self.btnPlanoInclinadoPolea.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPlanoInclinadoPolea.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnPlanoInclinadoPolea.setObjectName("btnPlanoInclinadoPolea")
        self.btnMura = QtWidgets.QPushButton(self.centralwidget)
        self.btnMura.setGeometry(QtCore.QRect(220, 50, 121, 61))
        self.btnMura.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMura.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnMura.setObjectName("btnMura")
        self.btnPendulo = QtWidgets.QPushButton(self.centralwidget)
        self.btnPendulo.setGeometry(QtCore.QRect(220, 210, 121, 61))
        self.btnPendulo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPendulo.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnPendulo.setObjectName("btnPendulo")
        self.btnMurayaza = QtWidgets.QPushButton(self.centralwidget)
        self.btnMurayaza.setGeometry(QtCore.QRect(220, 130, 121, 61))
        self.btnMurayaza.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMurayaza.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnMurayaza.setObjectName("btnMurayaza")
        self.btnMuraxa = QtWidgets.QPushButton(self.centralwidget)
        self.btnMuraxa.setGeometry(QtCore.QRect(380, 50, 121, 61))
        self.btnMuraxa.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMuraxa.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnMuraxa.setObjectName("btnMuraxa")
        self.btnPenduloResorte = QtWidgets.QPushButton(self.centralwidget)
        self.btnPenduloResorte.setGeometry(QtCore.QRect(380, 210, 121, 61))
        self.btnPenduloResorte.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPenduloResorte.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnPenduloResorte.setObjectName("btnPenduloResorte")
        self.btnMura3 = QtWidgets.QPushButton(self.centralwidget)
        self.btnMura3.setGeometry(QtCore.QRect(380, 130, 121, 61))
        self.btnMura3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMura3.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnMura3.setObjectName("btnMura3")
        self.btnResorte = QtWidgets.QPushButton(self.centralwidget)
        self.btnResorte.setGeometry(QtCore.QRect(530, 210, 121, 61))
        self.btnResorte.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnResorte.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnResorte.setObjectName("btnResorte")
        self.btnMuraxaya = QtWidgets.QPushButton(self.centralwidget)
        self.btnMuraxaya.setGeometry(QtCore.QRect(530, 50, 121, 61))
        self.btnMuraxaya.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMuraxaya.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnMuraxaya.setObjectName("btnMuraxaya")
        self.btnPlanoInclinado = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlanoInclinado.setGeometry(QtCore.QRect(530, 130, 121, 61))
        self.btnPlanoInclinado.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPlanoInclinado.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnPlanoInclinado.setObjectName("btnPlanoInclinado")
        self.btnColisionLinealnelastica = QtWidgets.QPushButton(self.centralwidget)
        self.btnColisionLinealnelastica.setGeometry(QtCore.QRect(380, 290, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnColisionLinealnelastica.setFont(font)
        self.btnColisionLinealnelastica.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnColisionLinealnelastica.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnColisionLinealnelastica.setObjectName("btnColisionLinealnelastica")
        self.btnColisionLinealElastica = QtWidgets.QPushButton(self.centralwidget)
        self.btnColisionLinealElastica.setGeometry(QtCore.QRect(220, 290, 121, 61))
        self.btnColisionLinealElastica.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnColisionLinealElastica.setStyleSheet("QPushButton {\n"
"    background-color: #EDF2FE;\n"
"    color: #3D63DD;\n"
"    padding: 10px;\n"
"    border: 1px solid #3D63DD;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3D63DD;\n"
"    color: white;\n"
"}")
        self.btnColisionLinealElastica.setObjectName("btnColisionLinealElastica")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnMur.setText(_translate("MainWindow", "MUR"))
        self.btnMuraxaza.setText(_translate("MainWindow", "MURAXAZA"))
        self.btnPlanoInclinadoPolea.setText(_translate("MainWindow", "PLANO INCLINADO POLEA"))
        self.btnMura.setText(_translate("MainWindow", "MURA"))
        self.btnPendulo.setText(_translate("MainWindow", "PÉNDULO "))
        self.btnMurayaza.setText(_translate("MainWindow", "MURAYAZA"))
        self.btnMuraxa.setText(_translate("MainWindow", "MURAXA"))
        self.btnPenduloResorte.setText(_translate("MainWindow", "PÉNDULO RESORTE"))
        self.btnMura3.setText(_translate("MainWindow", "MURA3"))
        self.btnResorte.setText(_translate("MainWindow", "RESORTE"))
        self.btnMuraxaya.setText(_translate("MainWindow", "MURAXAYA"))
        self.btnPlanoInclinado.setText(_translate("MainWindow", "PLANO INCLINADO"))
        self.btnColisionLinealnelastica.setText(_translate("MainWindow", "COLISIÓN LINEAL INELÁSTICA "))
        self.btnColisionLinealElastica.setText(_translate("MainWindow", "COLISIÓN LINEAL ELÁSTICA "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
