# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\peral\OneDrive\Escritorio\solve-dynamic-\Windows\desingUi\mur.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogMur(object):
    def setupUi(self, DialogMur):
        DialogMur.setObjectName("DialogMur")
        DialogMur.resize(227, 293)
        DialogMur.setStyleSheet("background-color: #DFEAFF;")
        self.label = QtWidgets.QLabel(DialogMur)
        self.label.setGeometry(QtCore.QRect(30, 80, 111, 16))
        self.label.setObjectName("label")
        self.inptVelocidadInicial = QtWidgets.QLineEdit(DialogMur)
        self.inptVelocidadInicial.setGeometry(QtCore.QRect(30, 100, 161, 20))
        self.inptVelocidadInicial.setStyleSheet("background-color: white;")
        self.inptVelocidadInicial.setObjectName("inptVelocidadInicial")
        self.label_2 = QtWidgets.QLabel(DialogMur)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 131, 16))
        self.label_2.setObjectName("label_2")
        self.inptDistanciaLadrillos = QtWidgets.QLineEdit(DialogMur)
        self.inptDistanciaLadrillos.setGeometry(QtCore.QRect(30, 180, 161, 20))
        self.inptDistanciaLadrillos.setStyleSheet("background-color: white;")
        self.inptDistanciaLadrillos.setObjectName("inptDistanciaLadrillos")
        self.lblErrorDistanciaLadrillos = QtWidgets.QLabel(DialogMur)
        self.lblErrorDistanciaLadrillos.setGeometry(QtCore.QRect(30, 200, 131, 16))
        self.lblErrorDistanciaLadrillos.setObjectName("lblErrorDistanciaLadrillos")
        self.lblErrorVelocidadInicial = QtWidgets.QLabel(DialogMur)
        self.lblErrorVelocidadInicial.setGeometry(QtCore.QRect(30, 120, 131, 16))
        self.lblErrorVelocidadInicial.setText("")
        self.lblErrorVelocidadInicial.setObjectName("lblErrorVelocidadInicial")
        self.label_3 = QtWidgets.QLabel(DialogMur)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.btnSimular = QtWidgets.QPushButton(DialogMur)
        self.btnSimular.setGeometry(QtCore.QRect(30, 240, 75, 23))
        self.btnSimular.setStyleSheet("background-color: #3D63DD;\n"
"color: white;")
        self.btnSimular.setObjectName("btnSimular")
        self.btnCancelar = QtWidgets.QPushButton(DialogMur)
        self.btnCancelar.setGeometry(QtCore.QRect(110, 240, 75, 23))
        self.btnCancelar.setStyleSheet("background-color: #3D63DD;\n"
"color: white;")
        self.btnCancelar.setObjectName("btnCancelar")

        self.retranslateUi(DialogMur)
        QtCore.QMetaObject.connectSlotsByName(DialogMur)

    def retranslateUi(self, DialogMur):
        _translate = QtCore.QCoreApplication.translate
        DialogMur.setWindowTitle(_translate("DialogMur", "Mur"))
        self.label.setText(_translate("DialogMur", "Velocidad inicial"))
        self.label_2.setText(_translate("DialogMur", "Distancia entre ladrillos"))
        self.lblErrorDistanciaLadrillos.setText(_translate("DialogMur", ""))
        self.label_3.setText(_translate("DialogMur", "Movimiento Rectilineo Uniforme"))
        self.btnSimular.setText(_translate("DialogMur", "Simular"))
        self.btnCancelar.setText(_translate("DialogMur", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogMur = QtWidgets.QDialog()
    ui = Ui_DialogMur()
    ui.setupUi(DialogMur)
    DialogMur.show()
    sys.exit(app.exec_())
