# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\peral\OneDrive\Escritorio\solve-dynamic-\Windows\desingUi\mura.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogMura(object):
    def setupUi(self, DialogMura):
        DialogMura.setObjectName("DialogMura")
        DialogMura.resize(228, 354)
        DialogMura.setStyleSheet("background-color: #DFEAFF;")
        self.inptVelocidadInicial = QtWidgets.QLineEdit(DialogMura)
        self.inptVelocidadInicial.setGeometry(QtCore.QRect(30, 110, 161, 20))
        self.inptVelocidadInicial.setStyleSheet("background-color: white;")
        self.inptVelocidadInicial.setObjectName("inptVelocidadInicial")
        self.lblErrorVelocidadInicial = QtWidgets.QLabel(DialogMura)
        self.lblErrorVelocidadInicial.setGeometry(QtCore.QRect(30, 130, 131, 16))
        self.lblErrorVelocidadInicial.setText("")
        self.lblErrorVelocidadInicial.setObjectName("lblErrorVelocidadInicial")
        self.label_3 = QtWidgets.QLabel(DialogMura)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(DialogMura)
        self.label.setGeometry(QtCore.QRect(30, 90, 111, 16))
        self.label.setObjectName("label")
        self.inptPosicionX = QtWidgets.QLineEdit(DialogMura)
        self.inptPosicionX.setGeometry(QtCore.QRect(30, 180, 161, 20))
        self.inptPosicionX.setStyleSheet("background-color: white;")
        self.inptPosicionX.setObjectName("inptPosicionX")
        self.label_4 = QtWidgets.QLabel(DialogMura)
        self.label_4.setGeometry(QtCore.QRect(30, 160, 161, 16))
        self.label_4.setObjectName("label_4")
        self.lblErrorPosicionX = QtWidgets.QLabel(DialogMura)
        self.lblErrorPosicionX.setGeometry(QtCore.QRect(30, 200, 131, 16))
        self.lblErrorPosicionX.setText("")
        self.lblErrorPosicionX.setObjectName("lblErrorPosicionX")
        self.inptAceleracion = QtWidgets.QLineEdit(DialogMura)
        self.inptAceleracion.setGeometry(QtCore.QRect(30, 250, 161, 20))
        self.inptAceleracion.setStyleSheet("background-color: white;")
        self.inptAceleracion.setObjectName("inptAceleracion")
        self.label_5 = QtWidgets.QLabel(DialogMura)
        self.label_5.setGeometry(QtCore.QRect(30, 230, 161, 16))
        self.label_5.setObjectName("label_5")
        self.lblErrorAceleracion = QtWidgets.QLabel(DialogMura)
        self.lblErrorAceleracion.setGeometry(QtCore.QRect(30, 270, 131, 16))
        self.lblErrorAceleracion.setText("")
        self.lblErrorAceleracion.setObjectName("lblErrorAceleracion")
        self.btnSimular = QtWidgets.QPushButton(DialogMura)
        self.btnSimular.setGeometry(QtCore.QRect(30, 300, 75, 23))
        self.btnSimular.setStyleSheet("background-color: #3D63DD;\n"
"color: white;")
        self.btnSimular.setObjectName("btnSimular")
        self.btnCancelar = QtWidgets.QPushButton(DialogMura)
        self.btnCancelar.setGeometry(QtCore.QRect(110, 300, 75, 23))
        self.btnCancelar.setStyleSheet("background-color: #3D63DD;\n"
"color: white;")
        self.btnCancelar.setObjectName("btnCancelar")

        self.retranslateUi(DialogMura)
        QtCore.QMetaObject.connectSlotsByName(DialogMura)

    def retranslateUi(self, DialogMura):
        _translate = QtCore.QCoreApplication.translate
        DialogMura.setWindowTitle(_translate("DialogMura", "MURA"))
        self.label_3.setText(_translate("DialogMura", "Movimiento Rectilineo Uniforme Acelerado"))
        self.label.setText(_translate("DialogMura", "Velocidad inicial"))
        self.label_4.setText(_translate("DialogMura", "Ingrese la posicion en x inicial"))
        self.label_5.setText(_translate("DialogMura", "Ingrese la aceleracion"))
        self.btnSimular.setText(_translate("DialogMura", "Simular"))
        self.btnCancelar.setText(_translate("DialogMura", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogMura = QtWidgets.QDialog()
    ui = Ui_DialogMura()
    ui.setupUi(DialogMura)
    DialogMura.show()
    sys.exit(app.exec_())
