# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\peral\OneDrive\Escritorio\solve-dynamic-\Windows\desingUi\planoInclinadoPolea.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogPlanoInclinadoPolea(object):
    def setupUi(self, DialogPlanoInclinadoPolea):
        DialogPlanoInclinadoPolea.setObjectName("DialogPlanoInclinadoPolea")
        DialogPlanoInclinadoPolea.resize(225, 363)
        DialogPlanoInclinadoPolea.setStyleSheet("background-color: #DFEAFF;")
        self.label_3 = QtWidgets.QLabel(DialogPlanoInclinadoPolea)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.inptAnguloInclinacion = QtWidgets.QLineEdit(DialogPlanoInclinadoPolea)
        self.inptAnguloInclinacion.setGeometry(QtCore.QRect(30, 240, 161, 20))
        self.inptAnguloInclinacion.setStyleSheet("background-color: white;")
        self.inptAnguloInclinacion.setObjectName("inptAnguloInclinacion")
        self.inptMasaObjeto = QtWidgets.QLineEdit(DialogPlanoInclinadoPolea)
        self.inptMasaObjeto.setGeometry(QtCore.QRect(30, 100, 161, 20))
        self.inptMasaObjeto.setStyleSheet("background-color: white;")
        self.inptMasaObjeto.setObjectName("inptMasaObjeto")
        self.lblErrorAnguloInclinacion = QtWidgets.QLabel(DialogPlanoInclinadoPolea)
        self.lblErrorAnguloInclinacion.setGeometry(QtCore.QRect(30, 260, 131, 16))
        self.lblErrorAnguloInclinacion.setText("")
        self.lblErrorAnguloInclinacion.setObjectName("lblErrorAnguloInclinacion")
        self.lblErrorMasaObjeto = QtWidgets.QLabel(DialogPlanoInclinadoPolea)
        self.lblErrorMasaObjeto.setGeometry(QtCore.QRect(30, 120, 131, 16))
        self.lblErrorMasaObjeto.setText("")
        self.lblErrorMasaObjeto.setObjectName("lblErrorMasaObjeto")
        self.label_2 = QtWidgets.QLabel(DialogPlanoInclinadoPolea)
        self.label_2.setGeometry(QtCore.QRect(30, 220, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(DialogPlanoInclinadoPolea)
        self.label.setGeometry(QtCore.QRect(30, 80, 111, 16))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(DialogPlanoInclinadoPolea)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 111, 16))
        self.label_4.setObjectName("label_4")
        self.lblErrorMasaObjeto2 = QtWidgets.QLabel(DialogPlanoInclinadoPolea)
        self.lblErrorMasaObjeto2.setGeometry(QtCore.QRect(30, 190, 131, 16))
        self.lblErrorMasaObjeto2.setText("")
        self.lblErrorMasaObjeto2.setObjectName("lblErrorMasaObjeto2")
        self.inptMasaObjeto2 = QtWidgets.QLineEdit(DialogPlanoInclinadoPolea)
        self.inptMasaObjeto2.setGeometry(QtCore.QRect(30, 170, 161, 20))
        self.inptMasaObjeto2.setStyleSheet("background-color: white;")
        self.inptMasaObjeto2.setObjectName("inptMasaObjeto2")
        self.btnSimular = QtWidgets.QPushButton(DialogPlanoInclinadoPolea)
        self.btnSimular.setGeometry(QtCore.QRect(30, 300, 75, 23))
        self.btnSimular.setStyleSheet("background-color: #3D63DD;\n"
"color: white;")
        self.btnSimular.setObjectName("btnSimular")
        self.btnCancelar = QtWidgets.QPushButton(DialogPlanoInclinadoPolea)
        self.btnCancelar.setGeometry(QtCore.QRect(110, 300, 75, 23))
        self.btnCancelar.setStyleSheet("background-color: #3D63DD;\n"
"color: white;")
        self.btnCancelar.setObjectName("btnCancelar")

        self.retranslateUi(DialogPlanoInclinadoPolea)
        QtCore.QMetaObject.connectSlotsByName(DialogPlanoInclinadoPolea)

    def retranslateUi(self, DialogPlanoInclinadoPolea):
        _translate = QtCore.QCoreApplication.translate
        DialogPlanoInclinadoPolea.setWindowTitle(_translate("DialogPlanoInclinadoPolea", "Plano inclinado polea"))
        self.label_3.setText(_translate("DialogPlanoInclinadoPolea", "Plano inclinado polea"))
        self.label_2.setText(_translate("DialogPlanoInclinadoPolea", "Angulo de inclinacion"))
        self.label.setText(_translate("DialogPlanoInclinadoPolea", "Masa del  objeto 1"))
        self.label_4.setText(_translate("DialogPlanoInclinadoPolea", "Masa del  objeto 2"))
        self.btnSimular.setText(_translate("DialogPlanoInclinadoPolea", "Simular"))
        self.btnCancelar.setText(_translate("DialogPlanoInclinadoPolea", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogPlanoInclinadoPolea = QtWidgets.QDialog()
    ui = Ui_DialogPlanoInclinadoPolea()
    ui.setupUi(DialogPlanoInclinadoPolea)
    DialogPlanoInclinadoPolea.show()
    sys.exit(app.exec_())
